display:
  default:
    display_options:
      fields:
        import_id:
          label: ID
        uid:
          label: Defnyddiwr
        sources_value:
          label: Ffynonellau
      pager:
        options:
          tags:
            next: '>>'
            previous: '<<'
          expose:
            items_per_page_label: 'Eitemau pob tudalen'
            offset_label: Ongli
      exposed_form:
        options:
          submit_button: Ceisio
          reset_button_label: Ailosod
          exposed_sorts_label: 'Dosbarthu drwy'
      arguments:
        feed:
          exception:
            title: 'I gyd'
  page_1:
    display_title: Tudalen
    display_options:
      menu:
        title: Arolwg
