_core:
  default_config_hash: ae8AQLsAFXvfcLPmE4YUBcxThAqf7psqRTHzhccslls
site_key: ''
secret_key: ''
verify_hostname: true
default_challenge: captcha\Math
error_message: 'Antibot verification failed.'
cacheable: false
library_use_recaptcha_net: false
hide_badge: false
