parameters:
  - name: schemaMigration
    displayName: Run SQL Database Migration
    type: boolean
    default: true
  - name: deployPHP
    displayName: Deploy the PHP
    type: boolean
    default: true
  - name: deployCrond
    displayName: Deploy the Crond
    type: boolean
    default: false
  - name: deployTika
    displayName: Deploy the Tika
    type: boolean
    default: false


pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.30.0
  pipelines:
    - pipeline: build
      source: Build
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'cd'
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test
    globalVariables:
      - template: .azure/pipelines/variables.yml@self
    deploymentStages:
      - name: Stage
        deploymentJobs:
          - name: Stage PHP
            condition: ${{ eq(parameters.deployPHP, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-library-service-php-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: libraryservice/php
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: PHP
                  appUrl: $(deploySlotOutputs.slotUrl)/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
          - name: Stage Crond
            condition: ${{ eq(parameters.deployCrond, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-library-service-crond-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: libraryservice/crond
          - name: Stage Tika
            condition: ${{ eq(parameters.deployTika, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-library-service-tika-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: libraryservice/tika
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Tika
                  appUrl: $(deploySlotOutputs.slotUrl)/version
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
      - name: Deploy
        dependsOn:
          - Stage
        deploymentJobs:
          - name: Deploy PHP
            condition: ${{ eq(parameters.deployPHP, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-library-service-php-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: PHP
                  appUrl: https://pins-app-library-service-php-$(ENVIRONMENT).azurewebsites.net/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
          - name: Deploy Crond
            condition: ${{ eq(parameters.deployCrond, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-library-service-crond-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
          - name: Deploy Tika
            condition: ${{ eq(parameters.deployTika, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-library-service-tika-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Tika
                  appUrl: https://pins-app-library-service-tika-$(ENVIRONMENT).azurewebsites.net/version
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)


