<?php

namespace Drupal\pins_search_azure\Services;

use Drupal\Core\Database\Connection;
use Drupal\Core\Logger\LoggerChannelFactoryInterface;

/**
 * Records Azure OpenAI token usage generated while indexing.
 */
class TokenUsageTracker {

  protected $database;
  protected $logger;

  public function __construct(Connection $database, LoggerChannelFactoryInterface $logger_factory) {
    $this->database = $database;
    $this->logger = $logger_factory->get('pins_search_azure');
  }

  /**
   * Persists a single item's token usage to the custom tracking table.
   *
   * Upserts on (index_id, item_id) so each node keeps exactly one row that
   * reflects its most recent indexing pass, rather than accumulating with
   * every re-index.
   */
  public function record(string $index_id, string $item_id, int $field_count, int $prompt_tokens, int $total_tokens): void {
    try {
      $this->database->merge('pins_search_azure_token_usage')
        ->keys([
          'index_id' => $index_id,
          'item_id' => $item_id,
        ])
        ->fields([
          'field_count' => $field_count,
          'prompt_tokens' => $prompt_tokens,
          'total_tokens' => $total_tokens,
          'created' => \Drupal::time()->getRequestTime(),
        ])
        ->execute();
    }
    catch (\Exception $e) {
      $this->logger->error('Failed to record token usage for @item: @msg', ['@item' => $item_id, '@msg' => $e->getMessage()]);
    }
  }

  /**
   * Logs token usage generated by vectorizing a live search query.
   *
   * Each search is appended as its own row (not upserted), since the same
   * keywords can legitimately be searched many times.
   */
  public function recordQuery(string $index_id, string $query_text, int $prompt_tokens, int $total_tokens): void {
    try {
      $this->database->insert('pins_search_azure_query_usage')
        ->fields([
          'index_id' => $index_id,
          // Truncate to fit the column; only used for display purposes.
          'query_text' => mb_substr($query_text, 0, 255),
          'prompt_tokens' => $prompt_tokens,
          'total_tokens' => $total_tokens,
          'created' => \Drupal::time()->getRequestTime(),
        ])
        ->execute();
    }
    catch (\Exception $e) {
      $this->logger->error('Failed to record query token usage: @msg', ['@msg' => $e->getMessage()]);
    }
  }
}
