label: Sylwadau
display:
  default:
    display_title: Diofyn
    display_options:
      title: Sylwadau
      fields:
        subject:
          label: Testun
        name:
          label: Awdur
        entity_id:
          label: 'Wedi ei gofnodi yn'
        changed:
          label: Newidwyd
        operations:
          label: Gweithrediad
      pager:
        options:
          tags:
            next: 'nesaf >'
            previous: '< blaenorol'
            first: Cyntaf
            last: 'olaf >>'
          expose:
            items_per_page_label: 'Eitemau pob tudalen'
            offset_label: Ongli
      exposed_form:
        options:
          submit_button: Hidlydd
          reset_button_label: Ailosod
          exposed_sorts_label: 'Dosbarthu drwy'
      empty:
        area_text_custom:
          content: 'Dim sylwadau ar gael'
      filters:
        subject:
          expose:
            label: Testun
        langcode:
          expose:
            label: Iaith
      use_more_text: mwy
  page_published:
    display_title: 'Sylwadau wedi eu cyhoeddi'
    display_options:
      menu:
        title: Sylwadau
  page_unapproved:
    display_options:
      fields:
        subject:
          label: Testun
        name:
          label: Awdur
        entity_id:
          label: 'Wedi ei gofnodi yn'
        changed:
          label: Newidwyd
        operations:
          label: Gweithrediad
      filters:
        subject:
          expose:
            label: Testun
        langcode:
          expose:
            label: Iaith
