label: Cynnwys
display:
  default:
    display_title: Diofyn
    display_options:
      title: Cynnwys
      fields:
        title:
          label: Pennawd
        name:
          label: Awdur
        status:
          label: Statws
          settings:
            format_custom_true: 'Wedi ei gyhoeddi'
        changed:
          label: Newidwyd
        operations:
          label: Gweithrediad
      exposed_form:
        options:
          submit_button: Hidlydd
          reset_button_label: Ailosod
          exposed_sorts_label: 'Dosbarthu drwy'
      filters:
        title:
          expose:
            label: Pennawd
        status:
          expose:
            label: Statws
          group_info:
            group_items:
              1:
                title: 'Wedi ei gyhoeddi'
        langcode:
          expose:
            label: Iaith
  page_1:
    display_title: Tudalen
    display_options:
      menu:
        title: Cynnwys
      tab_options:
        title: Cynnwys
