display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Ceisio
          reset_button_label: Ailosod
          exposed_sorts_label: 'Dosbarthu drwy'
      pager:
        options:
          tags:
            previous: '< blaenorol'
            next: 'nesaf >'
            first: Cyntaf
            last: 'olaf >>'
          expose:
            items_per_page_label: 'Eitemau pob tudalen'
            offset_label: Ongli
      fields:
        type:
          label: Math
        title:
          label: Pennawd
        name:
          label: Awdur
  page_1:
    display_title: Tudalen
