settings:
  default_submit_button_label: Cyflwyno
  default_reset_button_label: Ailosod
  default_delete_button_label: Dileu
  default_wizard_start_label: Dechrau
  default_preview_next_button_label: Rhagolwg
  default_preview_label: Rhagolwg
  dialog_options:
    normal:
      title: Cyffredin
element:
  default_more_title: Mwy
