adding:
  dependencies:
    module:
      - feeds_log
  third_party_settings:
    feeds_log:
      status: true
      operations:
        created: created
        skipped: skipped
        failed: failed
        cleaned: cleaned
      items: {  }
      source: true
removing: {  }
