contexts:
  -
    context: ''
    translations:
      -
        source: 'Ajouter aux favoris'
        translation: 'Add to bookmark'
      -
        source: 'Home username'
        translation: 'email address'
      -
        source: 'Log in'
        translation: 'Sign in'
      -
        source: 'Log out'
        translation: 'Sign out'
      -
        source: 'Retirer des favoris'
        translation: 'Remove from bookmark'
      -
        source: 'Username or email address'
        translation: 'Email address'
      -
        source: 'Create Article'
        translation: 'Add Article'
      -
        source: 'Create Hard copy'
        translation: 'Add Hard copy'
      -
        source: 'Create Hard copy loan'
        translation: 'Add Hard copy loan'
      -
        source: 'Create PDF'
        translation: 'Add PDF'
      -
        source: 'Create Basic page'
        translation: 'Add Basic page'
